/**
 * The position index as it stood before the compact schema.
 *
 * This is a fixture, not a copy of the current schema with a flag: it is
 * written out because the thing under test is a migration *from* it, and a
 * migration test whose "before" state is generated by the code being tested
 * proves only that the code agrees with itself. The DDL below is the
 * `positions` table exactly as `companion/src/database.mjs` declared it at
 * commit 24a30ac, which is the last commit before the compact schema existed.
 *
 * Only the tables the migration touches are here. The rest of the schema is
 * created by `GameDatabase` when the fixture is opened, which is also what
 * happens to a real collection.
 */

import { DatabaseSync } from 'node:sqlite';

/** `positions` as of 24a30ac. Text columns, and the two text indexes. */
export const TEXT_SCHEMA_DDL = `
CREATE TABLE IF NOT EXISTS games (
  id            INTEGER PRIMARY KEY,
  fingerprint   TEXT NOT NULL UNIQUE,
  white         TEXT NOT NULL,
  black         TEXT NOT NULL,
  white_key     TEXT NOT NULL,
  black_key     TEXT NOT NULL,
  result        TEXT NOT NULL,
  date          TEXT,
  year          INTEGER,
  event         TEXT,
  site          TEXT,
  round         TEXT,
  white_rating  INTEGER,
  black_rating  INTEGER,
  max_rating    INTEGER,
  eco           TEXT,
  opening       TEXT,
  ply_count     INTEGER,
  imported_at   INTEGER NOT NULL,
  classified_eco       TEXT,
  classified_name      TEXT,
  classified_variation TEXT,
  classified_ply       INTEGER,
  classified_with      TEXT
);

CREATE TABLE IF NOT EXISTS game_content (
  game_id       INTEGER PRIMARY KEY REFERENCES games(id) ON DELETE CASCADE,
  pgn           TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS positions (
  position_key  TEXT NOT NULL,
  game_id       INTEGER NOT NULL REFERENCES games(id) ON DELETE CASCADE,
  ply           INTEGER NOT NULL,
  move_uci      TEXT NOT NULL,
  move_san      TEXT NOT NULL,
  mover         TEXT NOT NULL,
  fen           TEXT,
  node_id       TEXT,
  pawn_skeleton TEXT,
  structure_signature TEXT,
  structure_claims TEXT,
  year_key INTEGER,
  rating_key INTEGER,
  result_key TEXT
);

CREATE INDEX IF NOT EXISTS positions_key  ON positions(position_key);
CREATE INDEX IF NOT EXISTS positions_game ON positions(game_id);
CREATE INDEX IF NOT EXISTS positions_pawn_skeleton ON positions(pawn_skeleton)
  WHERE pawn_skeleton IS NOT NULL;
CREATE INDEX IF NOT EXISTS positions_structure_signature ON positions(structure_signature)
  WHERE structure_signature IS NOT NULL;
`;

const START = 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq -';

/**
 * Write a text-schema collection with `games` games and `pliesPerGame` indexed
 * positions each.
 *
 * The structural values repeat on purpose and at roughly the ratio the real
 * collection showed — a handful of distinct skeletons and claim sets across
 * thousands of rows — because the saving being tested is entirely a
 * consequence of that repetition, and a fixture of distinct values would test
 * a migration nobody would run.
 */
export function writeTextSchemaFixture(file, { games = 4, pliesPerGame = 5 } = {}) {
  const db = new DatabaseSync(file);
  db.exec(TEXT_SCHEMA_DDL);
  const insertGame = db.prepare(
    `INSERT INTO games (fingerprint, white, black, white_key, black_key, result,
                        date, year, event, site, round, white_rating, black_rating,
                        max_rating, eco, opening, ply_count, imported_at)
     VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,
  );
  const insertContent = db.prepare('INSERT INTO game_content (game_id, pgn) VALUES (?,?)');
  const insertPosition = db.prepare(
    `INSERT INTO positions (position_key, game_id, ply, move_uci, move_san, mover,
                            fen, node_id, pawn_skeleton, structure_signature,
                            structure_claims, year_key, rating_key, result_key)
     VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,
  );

  const skeletons = ['8/8/8/3p4/3P4/8/8/8', '8/8/4p3/3p4/3P4/8/8/8', '8/8/8/8/8/8/8/8'];
  const signatures = ['material:none|pawns:d4,d5', 'material:none|pawns:d4,d5,e6'];
  const claimSets = [
    JSON.stringify(['white:isolated:d4', 'open:c']),
    JSON.stringify(['black:backward:e6']),
    null,
  ];

  db.exec('BEGIN');
  for (let g = 1; g <= games; g += 1) {
    const year = 2000 + (g % 25);
    insertGame.run(
      `fixture-${g}`,
      `White ${g}`,
      `Black ${g}`,
      `white ${g}`,
      `black ${g}`,
      g % 3 === 0 ? '1/2-1/2' : g % 3 === 1 ? '1-0' : '0-1',
      `${year}.01.01`,
      year,
      'Fixture event',
      'Fixture site',
      String(g),
      2400 + (g % 100),
      2350 + (g % 100),
      2400 + (g % 100),
      'C20',
      'King Pawn',
      pliesPerGame,
      year,
    );
    insertContent.run(g, `[White "White ${g}"]\n\n1. e4 *`);
    for (let ply = 0; ply < pliesPerGame; ply += 1) {
      // A distinct key per ply, and the FEN that key plus two counters makes —
      // the relationship the compact schema stores instead of the string.
      const positionKey = ply === 0 ? START : `k${g}-${ply}/8/8/8/8/8/8/8 w - -`;
      insertPosition.run(
        positionKey,
        g,
        ply,
        'e2e4',
        'e4',
        ply % 2 === 0 ? 'w' : 'b',
        `${positionKey} ${ply} ${Math.floor(ply / 2) + 1}`,
        `n-${g}-${ply}`,
        skeletons[(g + ply) % skeletons.length],
        signatures[(g + ply) % signatures.length],
        claimSets[(g + ply) % claimSets.length],
        year,
        2400 + (g % 100),
        g % 3 === 0 ? '1/2-1/2' : g % 3 === 1 ? '1-0' : '0-1',
      );
    }
  }
  db.exec('COMMIT');
  db.close();
  return { games, positions: games * pliesPerGame };
}

/** Read every position back as plain text, for comparing across a migration. */
export function readTextPositions(file) {
  const db = new DatabaseSync(file);
  const compact = !db
    .prepare('PRAGMA table_info(positions)')
    .all()
    .some((row) => row.name === 'pawn_skeleton');
  const rows = db
    .prepare(
      compact
        ? `SELECT p.position_key, p.game_id, p.ply,
                  COALESCE(p.fen_literal, CASE WHEN p.halfmove IS NULL THEN NULL
                    ELSE p.position_key || ' ' || p.halfmove || ' ' || p.fullmove END) AS fen,
                  ks.value AS pawn_skeleton, gs.value AS structure_signature,
                  cs.value AS structure_claims
             FROM positions p
             LEFT JOIN pawn_skeletons ks ON ks.id = p.pawn_skeleton_id
             LEFT JOIN structure_signatures gs ON gs.id = p.structure_signature_id
             LEFT JOIN structure_claim_sets cs ON cs.id = p.structure_claims_id
            ORDER BY p.game_id, p.ply`
        : `SELECT position_key, game_id, ply, fen, pawn_skeleton,
                  structure_signature, structure_claims
             FROM positions ORDER BY game_id, ply`,
    )
    .all()
    .map((row) => ({ ...row }));
  db.close();
  return rows;
}
