/**
 * The historical player roster.
 *
 * Kingfisher's reference packs are built from an open archive that begins in
 * 2020. That is a perfectly good elite database and a hopeless history of
 * chess: it contains Carlsen, Gukesh and Praggnanandhaa, and does not contain
 * Morphy, Capablanca, Tal or Fischer at all.
 *
 * This is the list that fixes the second problem without pretending to fix the
 * first. Each entry is a person and a handful of facts about them — dates,
 * title, what they won. It is *not* games. Where the installed sources hold
 * games for someone here, the catalog shows the real count; where they hold
 * none, it says none. Nothing on this list implies a game exists.
 *
 * `aliases` are the other spellings the same person appears under in PGN, and
 * they are the only mechanism by which a roster entry is attached to a pack
 * row. Kingfisher does not decide that two similar names are one person — that
 * remains the user's judgement, exactly as in Phase 12 — but a name written
 * down here has been checked, once, by a person.
 */

export type LegendRole =
  'world-champion' | 'fide-champion' | 'challenger' | 'women-champion' | 'pre-fide' | 'grandmaster';

export interface Legend {
  readonly name: string;
  readonly aliases: readonly string[];
  readonly title: string;
  readonly born: number;
  /** Omitted when the roster does not state one. */
  readonly died?: number;
  readonly roles: readonly LegendRole[];
  /** When they held the title, for the champions. */
  readonly reign?: string;
  readonly note: string;
  readonly fideId?: string;
}

const champion = (
  name: string,
  aliases: readonly string[],
  born: number,
  died: number | undefined,
  reign: string,
  note: string,
): Legend => ({
  name,
  aliases,
  title: 'GM',
  born,
  ...(died ? { died } : {}),
  roles: ['world-champion'],
  reign,
  note,
});

/** The undisputed lineage, in order. */
const WORLD_CHAMPIONS: readonly Legend[] = [
  champion(
    'Steinitz, Wilhelm',
    ['Steinitz, W', 'Wilhelm Steinitz', 'Steinitz'],
    1836,
    1900,
    '1886–1894',
    'The first world champion, and the first to write down positional principles as rules rather than taste.',
  ),
  champion(
    'Lasker, Emanuel',
    ['Lasker, Em', 'Emanuel Lasker', 'Lasker, E'],
    1868,
    1941,
    '1894–1921',
    'Held the title for twenty-seven years, longer than anyone before or since.',
  ),
  champion(
    'Capablanca, Jose Raul',
    ['Capablanca, Jose', 'Capablanca, J R', 'Jose Raul Capablanca', 'Capablanca'],
    1888,
    1942,
    '1921–1927',
    'Lost about thirty-five serious games in his whole career; the model for simple, clear technique.',
  ),
  champion(
    'Alekhine, Alexander',
    ['Alekhine, A', 'Alexander Alekhine', 'Aljechin, Alexander'],
    1892,
    1946,
    '1927–1935, 1937–1946',
    'The only champion to die holding the title. Combinative attacking play built on deep preparation.',
  ),
  champion(
    'Euwe, Max',
    ['Euwe, M', 'Max Euwe'],
    1901,
    1981,
    '1935–1937',
    'An amateur by profession — a mathematics teacher — and later president of FIDE.',
  ),
  champion(
    'Botvinnik, Mikhail',
    ['Botvinnik, M', 'Mikhail Botvinnik', 'Botvinnik, Mikhail M'],
    1911,
    1995,
    '1948–1957, 1958–1960, 1961–1963',
    'The patriarch of the Soviet school, and the first to treat preparation as engineering.',
  ),
  champion(
    'Smyslov, Vasily',
    ['Smyslov, V', 'Vassily Smyslov', 'Smyslov, Vassily'],
    1921,
    2010,
    '1957–1958',
    'Harmonious positional play and a famous endgame technique; a candidate again at fifty-two.',
  ),
  champion(
    'Tal, Mikhail',
    ['Tal, M', 'Mikhail Tal', 'Tal, Mihail'],
    1936,
    1992,
    '1960–1961',
    'The Magician from Riga. Sacrificed on intuition and calculation nobody else could follow.',
  ),
  champion(
    'Petrosian, Tigran V',
    ['Petrosian, Tigran', 'Petrosian, T', 'Tigran Petrosian', 'Petrosian, Tigran Vartanovich'],
    1929,
    1984,
    '1963–1969',
    'Prophylaxis carried to its limit: he was famous for the moves that stopped games happening.',
  ),
  champion(
    'Spassky, Boris',
    ['Spassky, B', 'Boris Spassky', 'Spassky, Boris V'],
    1937,
    2025,
    '1969–1972',
    'A universal style, at home in any structure. Lost the 1972 match in Reykjavik.',
  ),
  champion(
    'Fischer, Robert James',
    ['Fischer, Bobby', 'Fischer, R', 'Bobby Fischer', 'Fischer, Robert J'],
    1943,
    2008,
    '1972–1975',
    'Took the title from the Soviet system single-handed, then never defended it.',
  ),
  champion(
    'Karpov, Anatoly',
    ['Karpov, A', 'Anatoly Karpov', 'Karpov, Anatoly E'],
    1951,
    undefined,
    '1975–1985 (FIDE 1993–1999)',
    'The purest positional player of the modern era; five world championship matches against Kasparov.',
  ),
  champion(
    'Kasparov, Garry',
    ['Kasparov, G', 'Garry Kasparov', 'Kasparov, Gary'],
    1963,
    undefined,
    '1985–2000',
    'Held the highest rating in the world for twenty years, and made opening preparation a weapon.',
  ),
  champion(
    'Kramnik, Vladimir',
    ['Kramnik, V', 'Vladimir Kramnik'],
    1975,
    undefined,
    '2000–2007',
    'Took the title from Kasparov with the Berlin Wall, without losing a game in the match.',
  ),
  champion(
    'Anand, Viswanathan',
    ['Anand, V', 'Viswanathan Anand', 'Anand, Vishy'],
    1969,
    undefined,
    '2007–2013 (FIDE 2000–2002)',
    'The first Indian world champion, and the fastest calculator of his generation.',
  ),
  champion(
    'Carlsen, Magnus',
    ['Carlsen, M', 'Magnus Carlsen'],
    1990,
    undefined,
    '2013–2023',
    'The highest rating ever achieved, and a style built on grinding tiny advantages for a hundred moves.',
  ),
  champion(
    'Ding, Liren',
    ['Ding Liren', 'Ding, L'],
    1992,
    undefined,
    '2023–2024',
    'The first Chinese world champion, after Carlsen declined to defend the title.',
  ),
  champion(
    'Gukesh D',
    ['Gukesh, D', 'Gukesh Dommaraju', 'D Gukesh', 'Gukesh, Dommaraju'],
    2006,
    undefined,
    '2024–',
    'The youngest undisputed world champion, at eighteen.',
  ),
];

const other = (
  name: string,
  aliases: readonly string[],
  title: string,
  born: number,
  died: number | undefined,
  roles: readonly LegendRole[],
  note: string,
  reign?: string,
): Legend => ({
  name,
  aliases,
  title,
  born,
  ...(died ? { died } : {}),
  roles,
  ...(reign ? { reign } : {}),
  note,
});

/** Champions of the 1993–2006 split, who held the FIDE title but not the lineage. */
const FIDE_CHAMPIONS: readonly Legend[] = [
  other(
    'Khalifman, Alexander',
    ['Khalifman, A'],
    'GM',
    1966,
    undefined,
    ['fide-champion'],
    'Won the 1999 FIDE knockout in Las Vegas.',
    '1999–2000',
  ),
  other(
    'Ponomariov, Ruslan',
    ['Ponomariov, R'],
    'GM',
    1983,
    undefined,
    ['fide-champion'],
    'FIDE champion at eighteen, the youngest before Gukesh.',
    '2002–2004',
  ),
  other(
    'Kasimdzhanov, Rustam',
    ['Kasimdzhanov, R'],
    'GM',
    1979,
    undefined,
    ['fide-champion'],
    'Won the 2004 knockout in Tripoli; later Anand’s second.',
    '2004–2005',
  ),
  other(
    'Topalov, Veselin',
    ['Topalov, V'],
    'GM',
    1975,
    undefined,
    ['fide-champion', 'challenger'],
    'FIDE champion in 2005 and world number one; challenger in 2006 and 2010.',
    '2005–2006',
  ),
];

const WOMEN_CHAMPIONS: readonly Legend[] = [
  other(
    'Menchik, Vera',
    ['Menchik, V'],
    '',
    1906,
    1944,
    ['women-champion', 'pre-fide'],
    'The first women’s world champion, and the first woman to beat reigning male champions.',
    '1927–1944',
  ),
  other(
    'Rudenko, Lyudmila',
    ['Rudenko, L'],
    '',
    1904,
    1986,
    ['women-champion'],
    'Won the first post-war women’s championship tournament.',
    '1950–1953',
  ),
  other(
    'Bykova, Elisaveta',
    ['Bykova, E'],
    '',
    1913,
    1989,
    ['women-champion'],
    'Champion twice, either side of Rubtsova.',
    '1953–1956, 1958–1962',
  ),
  other(
    'Rubtsova, Olga',
    ['Rubtsova, O'],
    '',
    1909,
    1994,
    ['women-champion'],
    'Also a world champion at correspondence chess.',
    '1956–1958',
  ),
  other(
    'Gaprindashvili, Nona',
    ['Gaprindashvili, N'],
    'GM',
    1941,
    undefined,
    ['women-champion'],
    'Sixteen years as champion, and the first woman awarded the full grandmaster title.',
    '1962–1978',
  ),
  other(
    'Chiburdanidze, Maia',
    ['Chiburdanidze, M'],
    'GM',
    1961,
    undefined,
    ['women-champion'],
    'Champion at seventeen, and for thirteen years.',
    '1978–1991',
  ),
  other(
    'Xie, Jun',
    ['Xie Jun'],
    'GM',
    1970,
    undefined,
    ['women-champion'],
    'The first Chinese world champion of either title.',
    '1991–1996, 1999–2001',
  ),
  other(
    'Polgar, Susan',
    ['Polgar, Zsuzsa', 'Polgar, Zsuzsanna', 'Susan Polgar'],
    'GM',
    1969,
    undefined,
    ['women-champion'],
    'The eldest of the three Polgár sisters, and the first woman to earn the grandmaster title by norms.',
    '1996–1999',
  ),
  other(
    'Zhu, Chen',
    ['Zhu Chen'],
    'GM',
    1976,
    undefined,
    ['women-champion'],
    'Champion between Susan Polgár and Stefanova.',
    '2001–2004',
  ),
  other(
    'Stefanova, Antoaneta',
    ['Stefanova, A'],
    'GM',
    1979,
    undefined,
    ['women-champion'],
    'Bulgaria’s first women’s world champion.',
    '2004–2006',
  ),
  other(
    'Xu, Yuhua',
    ['Xu Yuhua'],
    'GM',
    1976,
    undefined,
    ['women-champion'],
    'Won the 2006 knockout in Yekaterinburg.',
    '2006–2008',
  ),
  other(
    'Kosteniuk, Alexandra',
    ['Kosteniuk, A'],
    'GM',
    1984,
    undefined,
    ['women-champion'],
    'Champion in 2008, and a long-standing top-ten player since.',
    '2008–2010',
  ),
  other(
    'Hou, Yifan',
    ['Hou Yifan'],
    'GM',
    1994,
    undefined,
    ['women-champion'],
    'Four-time champion and by a distance the strongest woman player of her generation.',
    '2010–2012, 2013–2015, 2016–2017',
  ),
  other(
    'Ushenina, Anna',
    ['Ushenina, A'],
    'GM',
    1985,
    undefined,
    ['women-champion'],
    'Ukraine’s women’s world champion, from the 2012 knockout.',
    '2012–2013',
  ),
  other(
    'Muzychuk, Mariya',
    ['Muzychuk, M'],
    'GM',
    1992,
    undefined,
    ['women-champion'],
    'Won the 2015 knockout in Sochi.',
    '2015–2016',
  ),
  other(
    'Tan, Zhongyi',
    ['Tan Zhongyi'],
    'GM',
    1991,
    undefined,
    ['women-champion'],
    'Champion in 2017, and challenger again in 2025.',
    '2017–2018',
  ),
  other(
    'Ju, Wenjun',
    ['Ju Wenjun'],
    'GM',
    1991,
    undefined,
    ['women-champion'],
    'The longest-reigning women’s champion of the modern era.',
    '2018–',
  ),
];

/** Players who reached a title match, or who plainly belong in any history. */
const GREATS: readonly Legend[] = [
  other(
    'Keres, Paul',
    ['Keres, P'],
    'GM',
    1916,
    1975,
    ['challenger'],
    'Second in four consecutive candidates cycles; the strongest player never to play a title match.',
  ),
  other(
    'Korchnoi, Viktor',
    ['Kortchnoi, Viktor', 'Korchnoi, V'],
    'GM',
    1931,
    2016,
    ['challenger'],
    'Twice a challenger, and still beating grandmasters at eighty.',
  ),
  other(
    'Bronstein, David',
    ['Bronstein, D'],
    'GM',
    1924,
    2006,
    ['challenger'],
    'Drew the 1951 match with Botvinnik and so did not take the title.',
  ),
  other(
    'Geller, Efim',
    ['Geller, E'],
    'GM',
    1925,
    1998,
    ['grandmaster'],
    'A plus score against most of the champions of his era.',
  ),
  other(
    'Larsen, Bent',
    ['Larsen, B'],
    'GM',
    1935,
    2010,
    ['grandmaster'],
    'The great Western hope of the 1960s, and an original at every move.',
  ),
  other(
    'Portisch, Lajos',
    ['Portisch, L'],
    'GM',
    1937,
    undefined,
    ['grandmaster'],
    'Hungary’s leading player for decades, and a candidate eight times.',
  ),
  other(
    'Reshevsky, Samuel',
    ['Reshevsky, S', 'Reshevsky, Samuel H'],
    'GM',
    1911,
    1992,
    ['grandmaster'],
    'A child prodigy of the 1920s who was still a candidate in the 1960s.',
  ),
  other(
    'Fine, Reuben',
    ['Fine, R'],
    'GM',
    1914,
    1993,
    ['grandmaster'],
    'Joint first at AVRO 1938, then left chess for psychology.',
  ),
  other(
    'Najdorf, Miguel',
    ['Najdorf, M'],
    'GM',
    1910,
    1997,
    ['grandmaster'],
    'Gave his name to the sharpest variation of the Sicilian.',
  ),
  other(
    'Gligoric, Svetozar',
    ['Gligoric, S'],
    'GM',
    1923,
    2012,
    ['grandmaster'],
    'Yugoslavia’s leading player and a great authority on the King’s Indian.',
  ),
  other(
    'Stein, Leonid',
    ['Stein, L'],
    'GM',
    1934,
    1973,
    ['grandmaster'],
    'Three-time Soviet champion, dead at thirty-eight.',
  ),
  other(
    'Taimanov, Mark',
    ['Taimanov, M'],
    'GM',
    1926,
    2016,
    ['grandmaster'],
    'A concert pianist as well as a grandmaster; lost 6–0 to Fischer in 1971.',
  ),
  other(
    'Polugaevsky, Lev',
    ['Polugaevsky, L'],
    'GM',
    1934,
    1995,
    ['grandmaster'],
    'Opening analysis of a depth nobody had attempted before him.',
  ),
  other(
    'Nezhmetdinov, Rashid',
    ['Nezhmetdinov, R'],
    'IM',
    1912,
    1974,
    ['grandmaster'],
    'Never a grandmaster, and the author of some of the most violent attacking games ever played.',
  ),
  other(
    'Averbakh, Yuri',
    ['Averbakh, Y'],
    'GM',
    1922,
    2022,
    ['grandmaster'],
    'Endgame theorist, and the first grandmaster to reach a hundred.',
  ),
  other(
    'Flohr, Salo',
    ['Flohr, S'],
    'GM',
    1908,
    1983,
    ['grandmaster'],
    'A title challenger-designate in 1939, until the war removed the match.',
  ),
  other(
    'Boleslavsky, Isaak',
    ['Boleslavsky, I'],
    'GM',
    1919,
    1977,
    ['grandmaster'],
    'His treatment of the Sicilian gave the Boleslavsky Wall its name.',
  ),
  other(
    'Kotov, Alexander',
    ['Kotov, A'],
    'GM',
    1913,
    1981,
    ['grandmaster'],
    'Wrote “Think Like a Grandmaster”, and the tree of analysis with it.',
  ),
  other(
    'Lilienthal, Andor',
    ['Lilienthal, A'],
    'GM',
    1911,
    2010,
    ['grandmaster'],
    'Beat Capablanca with a queen sacrifice in 1935 and lived to ninety-nine.',
  ),
  other(
    'Gelfand, Boris',
    ['Gelfand, B'],
    'GM',
    1968,
    undefined,
    ['challenger'],
    'Challenger in 2012, and a candidate across four decades.',
  ),
  other(
    'Short, Nigel D',
    ['Short, N', 'Short, Nigel'],
    'GM',
    1965,
    undefined,
    ['challenger'],
    'Challenged Kasparov in 1993, the match that split the title.',
  ),
  other(
    'Timman, Jan H',
    ['Timman, J', 'Timman, Jan'],
    'GM',
    1951,
    undefined,
    ['challenger'],
    'The best player in the West through the 1980s.',
  ),
  other(
    'Beliavsky, Alexander G',
    ['Beliavsky, A'],
    'GM',
    1953,
    undefined,
    ['grandmaster'],
    'Four-time Soviet champion and a candidate three times.',
  ),
  other(
    'Andersson, Ulf',
    ['Andersson, U'],
    'GM',
    1951,
    undefined,
    ['grandmaster'],
    'Endgame technique so patient that draws became a strategy.',
  ),
  other(
    'Polgar, Judit',
    ['Polgar, J', 'Judit Polgar'],
    'GM',
    1976,
    undefined,
    ['grandmaster'],
    'The strongest woman player in history, who never played in the women’s events.',
  ),
  other(
    'Ivanchuk, Vasyl',
    ['Ivanchuk, V', 'Ivanchuk, Vassily', 'Vasyl Ivanchuk'],
    'GM',
    1969,
    undefined,
    ['grandmaster'],
    'World number two, a Chigorin of the modern era, and still playing.',
  ),
  other(
    'Shirov, Alexei',
    ['Shirov, A'],
    'GM',
    1972,
    undefined,
    ['grandmaster'],
    'Beat Kramnik in a 1998 candidates match; “Fire on Board” is his.',
  ),
  other(
    'Leko, Peter',
    ['Leko, P'],
    'GM',
    1979,
    undefined,
    ['challenger'],
    'A point from the title in Brissago, 2004.',
  ),
  other(
    'Adams, Michael',
    ['Adams, Mi', 'Adams, M'],
    'GM',
    1971,
    undefined,
    ['grandmaster'],
    'England’s leading player for thirty years.',
  ),
  other(
    'Morozevich, Alexander',
    ['Morozevich, A'],
    'GM',
    1977,
    undefined,
    ['grandmaster'],
    'World number two with an opening repertoire nobody else would touch.',
  ),
  other(
    'Svidler, Peter',
    ['Svidler, P'],
    'GM',
    1976,
    undefined,
    ['grandmaster'],
    'Eight-time Russian champion.',
  ),
  other(
    'Grischuk, Alexander',
    ['Grischuk, A'],
    'GM',
    1983,
    undefined,
    ['grandmaster'],
    'Three candidates cycles, and the sharpest blitz player of his generation.',
  ),
  other(
    'Aronian, Levon',
    ['Aronian, L'],
    'GM',
    1982,
    undefined,
    ['grandmaster'],
    'World number two, and the most inventive middlegame player of the 2010s.',
  ),
  other(
    'Nakamura, Hikaru',
    ['Nakamura, H'],
    'GM',
    1987,
    undefined,
    ['grandmaster'],
    'Five-time US champion, and the player who took chess to streaming.',
  ),
  other(
    'Caruana, Fabiano',
    ['Caruana, F'],
    'GM',
    1992,
    undefined,
    ['challenger'],
    'Drew all twelve classical games of the 2018 title match.',
  ),
  other(
    'Vachier-Lagrave, Maxime',
    ['Vachier Lagrave, Maxime', 'Vachier-Lagrave, M'],
    'GM',
    1990,
    undefined,
    ['grandmaster'],
    'The world’s foremost authority on the Najdorf and the Grünfeld.',
  ),
  other(
    'Nepomniachtchi, Ian',
    ['Nepomniachtchi, I'],
    'GM',
    1990,
    undefined,
    ['challenger'],
    'Challenger twice, in 2021 and 2023.',
  ),
  other(
    'Giri, Anish',
    ['Giri, A'],
    'GM',
    1994,
    undefined,
    ['grandmaster'],
    'A candidate three times, and the most thorough preparer in the top ten.',
  ),
  other(
    'So, Wesley',
    ['So, W'],
    'GM',
    1993,
    undefined,
    ['grandmaster'],
    'World Fischer Random champion and a three-time US champion.',
  ),
  other(
    'Firouzja, Alireza',
    ['Firouzja, A'],
    'GM',
    2003,
    undefined,
    ['grandmaster'],
    'The youngest player ever to pass 2800.',
  ),
  other(
    'Praggnanandhaa R',
    ['Praggnanandhaa, R', 'Praggnanandhaa'],
    'GM',
    2005,
    undefined,
    ['grandmaster'],
    'Beat Carlsen at twelve, and reached the 2023 World Cup final at eighteen.',
  ),
  other(
    'Erigaisi Arjun',
    ['Erigaisi, Arjun', 'Arjun Erigaisi'],
    'GM',
    2003,
    undefined,
    ['grandmaster'],
    'India’s second 2800 player.',
  ),
  other(
    'Abdusattorov, Nodirbek',
    ['Abdusattorov, N'],
    'GM',
    2004,
    undefined,
    ['grandmaster'],
    'World rapid champion at seventeen.',
  ),
];

/** Before FIDE, and before the world championship as an institution. */
const PRE_FIDE: readonly Legend[] = [
  other(
    'Philidor, Francois-Andre Danican',
    ['Philidor'],
    '',
    1726,
    1795,
    ['pre-fide'],
    'The strongest player of the eighteenth century, and the first to write that pawns are the soul of chess.',
  ),
  other(
    'La Bourdonnais, Louis Charles Mahe de',
    ['La Bourdonnais'],
    '',
    1795,
    1840,
    ['pre-fide'],
    'His 1834 series against McDonnell is the first great match in the record.',
  ),
  other(
    'Staunton, Howard',
    ['Staunton, H'],
    '',
    1810,
    1874,
    ['pre-fide'],
    'Organised the first international tournament, London 1851, and named a piece set.',
  ),
  other(
    'Anderssen, Adolf',
    ['Anderssen, A'],
    '',
    1818,
    1879,
    ['pre-fide'],
    'The Immortal and the Evergreen are his.',
  ),
  other(
    'Morphy, Paul',
    ['Morphy, P', 'Paul Morphy'],
    '',
    1837,
    1884,
    ['pre-fide'],
    'Understood development and open lines a generation before anyone else, then stopped playing at twenty-two.',
  ),
  other(
    'Paulsen, Louis',
    ['Paulsen, L'],
    '',
    1833,
    1891,
    ['pre-fide'],
    'A defensive and positional thinker among attackers; several openings still carry his name.',
  ),
  other(
    'Zukertort, Johannes',
    ['Zukertort, J'],
    '',
    1842,
    1888,
    ['pre-fide'],
    'Lost the first world championship match to Steinitz in 1886.',
  ),
  other(
    'Blackburne, Joseph Henry',
    ['Blackburne, J'],
    '',
    1841,
    1924,
    ['pre-fide'],
    '“The Black Death”, and Britain’s leading player for forty years.',
  ),
  other(
    'Chigorin, Mikhail',
    ['Chigorin, M', 'Tschigorin, Mikhail'],
    '',
    1850,
    1908,
    ['pre-fide'],
    'Twice challenged Steinitz, and founded the Russian school by arguing with the German one.',
  ),
  other(
    'Gunsberg, Isidor',
    ['Gunsberg, I'],
    '',
    1854,
    1930,
    ['pre-fide'],
    'Challenged Steinitz in 1890 and came within a point.',
  ),
  other(
    'Tarrasch, Siegbert',
    ['Tarrasch, S'],
    '',
    1862,
    1934,
    ['pre-fide'],
    'The teacher of Germany, whose rules were codified precisely so they could be broken later.',
  ),
  other(
    'Maroczy, Geza',
    ['Maroczy, G'],
    'GM',
    1870,
    1951,
    ['pre-fide'],
    'The Maróczy Bind, and a title challenge that never took place.',
  ),
  other(
    'Pillsbury, Harry Nelson',
    ['Pillsbury, H'],
    '',
    1872,
    1906,
    ['pre-fide'],
    'Won Hastings 1895 at his first international tournament, and died at thirty-three.',
  ),
  other(
    'Schlechter, Carl',
    ['Schlechter, C'],
    '',
    1874,
    1918,
    ['pre-fide'],
    'Drew a world championship match with Lasker in 1910 and so did not take the title.',
  ),
  other(
    'Marshall, Frank James',
    ['Marshall, F'],
    'GM',
    1877,
    1944,
    ['pre-fide'],
    'US champion for twenty-seven years, and the Marshall Attack.',
  ),
  other(
    'Rubinstein, Akiba',
    ['Rubinstein, A'],
    'GM',
    1880,
    1961,
    ['pre-fide'],
    'The finest rook endgame player who ever lived; the war took his title match away.',
  ),
  other(
    'Bernstein, Ossip',
    ['Bernstein, O'],
    'GM',
    1882,
    1962,
    ['pre-fide'],
    'A lawyer who twice lost everything to revolutions, and drew with Botvinnik at sixty-four.',
  ),
  other(
    'Spielmann, Rudolf',
    ['Spielmann, R'],
    '',
    1883,
    1942,
    ['pre-fide'],
    '“The Last Knight of the King’s Gambit”, and the author of The Art of Sacrifice.',
  ),
  other(
    'Vidmar, Milan',
    ['Vidmar, M'],
    'GM',
    1885,
    1962,
    ['pre-fide'],
    'An electrical engineer of international standing who was also a world-class player.',
  ),
  other(
    'Nimzowitsch, Aron',
    ['Nimzowitsch, A', 'Nimzowitsch, Aaron'],
    '',
    1886,
    1935,
    ['pre-fide'],
    'My System, blockade, overprotection, and the Nimzo-Indian.',
  ),
  other(
    'Tartakower, Savielly',
    ['Tartakower, S'],
    'GM',
    1887,
    1956,
    ['pre-fide'],
    'The wittiest writer chess has had, and a strong player besides.',
  ),
  other(
    'Bogoljubov, Efim',
    ['Bogoljubow, Efim', 'Bogoljubov, E'],
    'GM',
    1889,
    1952,
    ['challenger', 'pre-fide'],
    'Twice challenged Alekhine, in 1929 and 1934.',
  ),
  other(
    'Reti, Richard',
    ['Reti, R'],
    '',
    1889,
    1929,
    ['pre-fide'],
    'Hypermodern theory, the Réti Opening, and the most famous study in the literature.',
  ),
  other(
    'Grunfeld, Ernst',
    ['Grunfeld, E', 'Gruenfeld, Ernst'],
    'GM',
    1893,
    1962,
    ['pre-fide'],
    'Gave his name to a defence still played at the top today.',
  ),
];

export const LEGENDS: readonly Legend[] = [
  ...WORLD_CHAMPIONS,
  ...FIDE_CHAMPIONS,
  ...WOMEN_CHAMPIONS,
  ...GREATS,
  ...PRE_FIDE,
];

export const legendYears = (legend: Legend): string =>
  legend.died ? `${legend.born}–${legend.died}` : `b. ${legend.born}`;

/** Curated sets, for browsing rather than searching. */
export const LEGEND_GROUPS = [
  { id: 'world-champion', label: 'World champions', role: 'world-champion' as const },
  { id: 'women-champion', label: 'Women’s world champions', role: 'women-champion' as const },
  { id: 'fide-champion', label: 'FIDE champions (1993–2006)', role: 'fide-champion' as const },
  { id: 'challenger', label: 'Title challengers', role: 'challenger' as const },
  { id: 'pre-fide', label: 'Before FIDE', role: 'pre-fide' as const },
] as const;
