#!/usr/bin/env node
/**
 * Fetch the Stockfish WebAssembly builds into `public/engine/stockfish/`.
 *
 * The engine is not a dependency of this package: it is GPL-3.0 licensed and
 * about 15 MB, so it is downloaded on demand and kept out of version control.
 * The application degrades honestly when it is missing — the engine panel says
 * so and points here — rather than pretending to analyse.
 *
 *   node scripts/install-engine.mjs [--if-missing] [--full]
 */

import { createHash } from 'node:crypto';
import { createWriteStream } from 'node:fs';
import { mkdir, readFile, rm, stat, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { pipeline } from 'node:stream/promises';
import { Readable } from 'node:stream';
import { fileURLToPath } from 'node:url';

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const TARGET_DIR = join(ROOT, 'public', 'engine', 'stockfish');
const CDN = 'https://unpkg.com/stockfish@18.0.8/bin';

/**
 * `lite-single` runs anywhere. `lite-mt` needs SharedArrayBuffer, which needs
 * cross-origin isolation (see next.config.ts); the provider picks at runtime.
 *
 * The two `full` builds carry Stockfish's full-size evaluation network — the
 * same network the native binary runs — and weigh 113 MB each against the
 * lite builds' 7 MB. They are what makes a browser-only user's analysis
 * comparable with a native one, and they are opt-in (`--full`, or
 * `KINGFISHER_ENGINE_FULL=1`): the web deployment asks for them
 * (`vercel.json`); the desktop build does not, because its users have native
 * Stockfish 19 and no reason to carry a second copy of the network.
 *
 * Their `.wasm` is **not** copied into `public/`. Until Phase 72 it was, and
 * every deployment of the web application carried 226 MB of it: with a
 * deployment per push and thirty days of retention that was the whole of
 * Vercel's 10 GB deployment-storage allowance, spent on two files that never
 * change between one deployment and the next. The browser now fetches each
 * one from the address recorded below — the same npm package the installer
 * itself downloads from — through `stockfish-18-remote.js`, a same-origin
 * bootstrap that pins the bytes to the SHA-256 recorded here (`fetch`'s
 * `integrity`) and hands them to the engine's own loader. The 36 KB worker
 * script stays local: workers must be same-origin, and the CSP says so.
 *
 * The digests were taken from the files this script downloaded, and checked
 * against a second download of the same address. Change them only with the
 * version in the file name.
 */
const BUILDS = [
  {
    id: 'lite-single',
    label: 'Stockfish 18 Lite (single-threaded)',
    script: 'stockfish-18-lite-single.js',
    wasm: 'stockfish-18-lite-single.wasm',
    threads: false,
    network: 'lite',
  },
  {
    id: 'lite-mt',
    label: 'Stockfish 18 Lite (multi-threaded)',
    script: 'stockfish-18-lite.js',
    wasm: 'stockfish-18-lite.wasm',
    threads: true,
    network: 'lite',
  },
  {
    id: 'full-single',
    label: 'Stockfish 18 (single-threaded, full network)',
    script: 'stockfish-18-single.js',
    wasm: 'stockfish-18-single.wasm',
    threads: false,
    network: 'full',
    remote: {
      url: `${CDN}/stockfish-18-single.wasm`,
      sha256: 'f611ac05ddb248fe975a4f180ac9fec7f7fb650f8f17f5fe4230fcc0fe6419c7',
      bytes: 112992459,
    },
  },
  {
    id: 'full-mt',
    label: 'Stockfish 18 (multi-threaded, full network)',
    script: 'stockfish-18.js',
    wasm: 'stockfish-18.wasm',
    threads: true,
    network: 'full',
    remote: {
      url: `${CDN}/stockfish-18.wasm`,
      sha256: '8bef136a3d7a428b5cbc624459a2091fd3e750c22a48dad9ad3b292ac80373cb',
      bytes: 113007340,
    },
  },
];

/**
 * The bootstrap worker for a build whose `.wasm` lives at a recorded address.
 *
 * `nmrugg/stockfish.js` reads the `.wasm` address from the worker URL's hash
 * (and passes it on to the threads it spawns, as `#<url>,worker`), fetches it
 * with a bare `fetch(url)` and compiles it with `instantiateStreaming`. This
 * wrapper is loaded as the worker instead of the engine script, replaces
 * `fetch` for that one address with a request that carries the recorded
 * `integrity` — the browser refuses the bytes if they do not hash to it —
 * and normalises the content type `instantiateStreaming` insists on, then
 * imports the engine script, which runs exactly as it would have.
 *
 * The digest travels in the query string, which the engine drops when it
 * names its thread workers; that is fine, because threads receive the
 * compiled module from the main worker and never fetch the file.
 */
const remoteBootstrap = (script) => `/*
 * Kingfisher: loads ${script} with its .wasm fetched from the address in this
 * worker's URL hash and verified against the SHA-256 in its query string
 * before the engine compiles it. Generated by scripts/install-engine.mjs;
 * the engine itself is Stockfish.js (GPL-3.0-or-later), unmodified.
 */
(function () {
  var integrity = new URLSearchParams(self.location.search).get('integrity');
  var wasmUrl = decodeURIComponent(self.location.hash.slice(1).split(',')[0] || '');
  var originalFetch = self.fetch.bind(self);
  self.fetch = function (input, init) {
    var url = typeof input === 'string' ? input : input && input.url;
    if (url !== wasmUrl) return originalFetch(input, init);
    var options = Object.assign({}, init || {}, { mode: 'cors', credentials: 'omit' });
    if (integrity) options.integrity = integrity;
    return originalFetch(input, options).then(
      function (response) {
        if (!response.ok) {
          fail('the server answered ' + response.status + ' ' + response.statusText);
          return response;
        }
        var headers = new Headers(response.headers);
        headers.set('content-type', 'application/wasm');
        return new Response(response.body, {
          status: response.status,
          statusText: response.statusText,
          headers: headers,
        });
      },
      function (error) {
        fail(
          (error && error.message ? error.message : String(error)) +
            (integrity ? ' — the bytes must match the recorded SHA-256' : ''),
        );
        throw error;
      },
    );
  };
  // The engine's loader logs a failed fetch and then waits for nothing, so
  // the page would only learn of it from its handshake timeout. Thrown
  // outside the promise chain, the failure reaches the page as the worker's
  // error event, which the engine transport turns into a message at once.
  function fail(reason) {
    setTimeout(function () {
      throw new Error('The engine network could not be fetched from ' + wasmUrl + ': ' + reason);
    }, 0);
  }
  importScripts('${script}');
})();
`;

const bootstrapName = (script) => script.replace(/\.js$/, '-remote.js');

/** `fetch`'s integrity metadata: the algorithm and the digest in base64. */
const integrityOf = (sha256Hex) => `sha256-${Buffer.from(sha256Hex, 'hex').toString('base64')}`;

const ifMissing = process.argv.includes('--if-missing');
const wantFull = process.argv.includes('--full') || process.env.KINGFISHER_ENGINE_FULL === '1';

async function exists(path) {
  try {
    const info = await stat(path);
    return info.size > 0;
  } catch {
    return false;
  }
}

async function sha256File(path) {
  const hash = createHash('sha256');
  hash.update(await readFile(path));
  return hash.digest('hex');
}

async function download(name) {
  const destination = join(TARGET_DIR, name);
  if (await exists(destination)) {
    process.stdout.write(`  · ${name} (already present)\n`);
    return;
  }

  const url = `${CDN}/${name}`;
  const response = await fetch(url);
  if (!response.ok || !response.body) {
    throw new Error(`${response.status} ${response.statusText} while fetching ${url}`);
  }

  const temporary = `${destination}.partial`;
  await pipeline(Readable.fromWeb(response.body), createWriteStream(temporary));
  await rm(destination, { force: true });
  const { rename } = await import('node:fs/promises');
  await rename(temporary, destination);

  const info = await stat(destination);
  process.stdout.write(`  ✓ ${name} (${(info.size / 1e6).toFixed(1)} MB)\n`);
}

async function main() {
  const manifestPath = join(TARGET_DIR, 'manifest.json');
  if (ifMissing && (await exists(manifestPath))) {
    // `--if-missing` is satisfied by a lite-only manifest unless the full
    // network was asked for and is not there yet.
    if (!wantFull) return;
    try {
      const manifest = JSON.parse(await readFile(manifestPath, 'utf8'));
      if (manifest.builds?.some((build) => build.network === 'full')) return;
    } catch {
      // An unreadable manifest is rewritten below.
    }
  }

  await mkdir(TARGET_DIR, { recursive: true });
  process.stdout.write('Installing Stockfish 18 (GPL-3.0-or-later) into public/engine…\n');

  const installed = [];
  for (const build of BUILDS) {
    // Without `--full` the full-network builds are not listed — but ones a
    // previous `--full` run already set up here stay listed. `npm run
    // test:e2e` runs this script without the flag, and the first version of
    // this loop silently dropped the full-network engine from a developer's
    // manifest every time the browser suite ran.
    if (
      build.network === 'full' &&
      !wantFull &&
      !(await exists(join(TARGET_DIR, bootstrapName(build.script))))
    ) {
      continue;
    }
    try {
      await download(build.script);
      if (build.remote) {
        const bootstrap = bootstrapName(build.script);
        await writeFile(join(TARGET_DIR, bootstrap), remoteBootstrap(build.script));
        // A copy this machine already holds is checked against the record;
        // nothing is downloaded to check it, and nothing is deployed.
        const local = join(TARGET_DIR, build.wasm);
        if (await exists(local)) {
          const digest = await sha256File(local);
          if (digest !== build.remote.sha256) {
            throw new Error(
              `${build.wasm} on disk hashes to ${digest}, not the recorded ${build.remote.sha256}`,
            );
          }
        }
        process.stdout.write(
          `  ✓ ${build.wasm} from ${build.remote.url} (${(build.remote.bytes / 1e6).toFixed(1)} MB, fetched by the browser, sha256 ${build.remote.sha256.slice(0, 12)}…)\n`,
        );
        installed.push({
          id: build.id,
          label: build.label,
          script: `/engine/stockfish/${bootstrap}?integrity=${encodeURIComponent(
            integrityOf(build.remote.sha256),
          )}#${encodeURIComponent(build.remote.url)}`,
          threads: build.threads,
          network: build.network,
          bytes: build.remote.bytes,
          wasm: build.remote.url,
          sha256: build.remote.sha256,
        });
        continue;
      }
      await download(build.wasm);
      const info = await stat(join(TARGET_DIR, build.wasm));
      installed.push({
        id: build.id,
        label: build.label,
        script: `/engine/stockfish/${build.script}`,
        threads: build.threads,
        network: build.network,
        bytes: info.size,
      });
    } catch (error) {
      process.stdout.write(`  ! ${build.id} unavailable: ${error.message}\n`);
    }
  }

  if (installed.length === 0) {
    process.stdout.write(
      '\nNo engine builds could be downloaded. The application still runs; the\n' +
        'engine panel will report that analysis is unavailable.\n',
    );
    process.exitCode = ifMissing ? 0 : 1;
    return;
  }

  await writeFile(
    manifestPath,
    `${JSON.stringify(
      {
        engine: 'Stockfish 18',
        license: 'GPL-3.0-or-later',
        source: 'https://www.npmjs.com/package/stockfish (nmrugg/stockfish.js)',
        installedAt: new Date().toISOString(),
        builds: installed,
      },
      null,
      2,
    )}\n`,
  );
  process.stdout.write(`\nReady: ${installed.map((b) => b.id).join(', ')}\n`);
}

main().catch((error) => {
  process.stderr.write(`Engine install failed: ${error.message}\n`);
  process.exitCode = 1;
});
