/**
 * The move orders that actually reach a position.
 *
 * Everything here comes from something stored. A position can be reached by a
 * great many legal move orders, and enumerating them would be easy and
 * useless: the interesting fact is not that 1.Nf3 d5 2.d4 Nf6 3.c4 e6 *can*
 * transpose into the Queen's Gambit, it is that eleven games in your database
 * and one of your study chapters got there that way. So no route is ever
 * generated by search — each one is read off a game the user imported or a
 * chapter they wrote.
 *
 * Repertoires are deliberately not a source. A repertoire is a map from
 * positions to intended moves rather than a sequence of them (ADR 0010), so it
 * holds no move order to report; inventing a path through the graph would be
 * exactly the speculation this module refuses to do.
 */

import { positionKey } from '@/chess/fen';
import { mustGetNode, nodePath } from '@/chess/tree/tree';
import type { GameTree } from '@/chess/tree/types';
import type { San } from '@/chess/types';

export type RouteSource = 'local-games' | 'sqlite' | 'study';

export interface TranspositionRouteView {
  /** The move order, in SAN, from the start of the game. */
  readonly moves: readonly San[];
  /** How many stored games or chapters arrived this way. */
  readonly count: number;
  readonly source: RouteSource;
  /** For a study route, the chapter it was found in. */
  readonly label?: string;
  /** Set for a study route, so clicking one can open that chapter's node. */
  readonly chapterId?: string;
  readonly nodeId?: string;
}

export const ROUTE_SOURCE_LABEL: Record<RouteSource, string> = {
  'local-games': 'your games',
  sqlite: 'SQLite collection',
  study: 'study',
};

/**
 * Every distinct move order in one tree that reaches the position.
 *
 * A chapter can reach the same position twice through different variations,
 * which is precisely the case worth showing, so this walks the whole tree
 * rather than the main line. The root is skipped: a chapter that *starts* at
 * the position has no move order to report, only a starting point.
 */
export function routesFromTree(
  tree: GameTree,
  key: string,
  context: { readonly label: string; readonly chapterId: string },
): readonly TranspositionRouteView[] {
  const found: TranspositionRouteView[] = [];
  const seen = new Set<string>();

  for (const nodeId of Object.keys(tree.nodes)) {
    if (nodeId === tree.rootId) continue;
    const node = tree.nodes[nodeId];
    if (!node || positionKey(node.fen) !== key) continue;

    const moves = nodePath(tree, nodeId)
      .slice(1)
      .map((id) => mustGetNode(tree, id).move?.san)
      .filter((san): san is San => san !== undefined);
    if (moves.length === 0) continue;

    const signature = moves.join(' ');
    if (seen.has(signature)) continue;
    seen.add(signature);
    found.push({
      moves,
      count: 1,
      source: 'study',
      label: context.label,
      chapterId: context.chapterId,
      nodeId,
    });
  }

  return found;
}

/**
 * Merge routes from several sources, keeping identical orders together.
 *
 * Counts from different sources are summed only when the move order is
 * identical, and the merged entry keeps every source that produced it — an
 * order found both in your games and in a chapter you wrote is one route with
 * two provenances, not two routes that look the same.
 */
export interface MergedRoute {
  readonly moves: readonly San[];
  readonly signature: string;
  readonly total: number;
  readonly bySource: readonly { readonly source: RouteSource; readonly count: number }[];
  /** The first study occurrence, if any, so the route can be opened. */
  readonly openable?: {
    readonly chapterId: string;
    readonly nodeId: string;
    readonly label: string;
  };
}

export function mergeRoutes(
  routes: readonly TranspositionRouteView[],
  currentMoves?: readonly San[],
): readonly MergedRoute[] {
  const current = currentMoves?.join(' ');
  const merged = new Map<string, MergedRoute>();

  for (const route of routes) {
    const signature = route.moves.join(' ');
    // The move order the user is already on is not a transposition to it.
    if (current !== undefined && signature === current) continue;

    const existing = merged.get(signature);
    if (!existing) {
      merged.set(signature, {
        moves: route.moves,
        signature,
        total: route.count,
        bySource: [{ source: route.source, count: route.count }],
        ...(route.chapterId && route.nodeId
          ? {
              openable: {
                chapterId: route.chapterId,
                nodeId: route.nodeId,
                label: route.label ?? 'Study',
              },
            }
          : {}),
      });
      continue;
    }

    const bySource = [...existing.bySource];
    const index = bySource.findIndex((entry) => entry.source === route.source);
    if (index >= 0) {
      bySource[index] = { source: route.source, count: bySource[index]!.count + route.count };
    } else {
      bySource.push({ source: route.source, count: route.count });
    }

    // The first study occurrence wins; later ones only add to the count.
    const openable =
      existing.openable ??
      (route.chapterId && route.nodeId
        ? { chapterId: route.chapterId, nodeId: route.nodeId, label: route.label ?? 'Study' }
        : undefined);

    merged.set(signature, {
      ...existing,
      total: existing.total + route.count,
      bySource,
      ...(openable ? { openable } : {}),
    });
  }

  /*
    Ordered by how often the order was actually played, then by how short it
    is. Frequency first because the common path is what a reader is checking
    for; length second because between two equally attested orders the
    shorter one is the one worth remembering.
  */
  return [...merged.values()].sort(
    (a, b) =>
      b.total - a.total ||
      a.moves.length - b.moves.length ||
      a.signature.localeCompare(b.signature),
  );
}

/** Move orders rendered the way a player writes them: `1.d4 Nf6 2.c4 e6`. */
export function formatRoute(moves: readonly San[], startingPly = 0): string {
  const parts: string[] = [];
  for (const [index, san] of moves.entries()) {
    const ply = startingPly + index;
    if (ply % 2 === 0) parts.push(`${Math.floor(ply / 2) + 1}.${san}`);
    else if (index === 0) parts.push(`${Math.floor(ply / 2) + 1}...${san}`);
    else parts.push(san);
  }
  return parts.join(' ');
}
