'use client';

/**
 * How else this position has been reached.
 *
 * Every route shown was played in a game the user imported or written into a
 * chapter they keep; nothing is derived by searching for legal orders. That
 * restraint is what makes the panel worth reading — "eleven of your games got
 * here this way" is evidence, "this is theoretically reachable" is trivia.
 *
 * Inspecting a route never changes the analysis. Clicking one opens the study
 * chapter it came from, which is a deliberate navigation; the current tree is
 * left exactly as it was, because a panel that rearranged your board when you
 * looked at it would be unusable during real research.
 */

import { useMemo, useState } from 'react';
import { useQuery } from '@tanstack/react-query';

import { positionKey } from '@/chess/fen';
import { mainlinePath, mustGetNode } from '@/chess/tree/tree';
import type { San } from '@/chess/types';
import { EmptyState, PanelBody, PanelHeader } from '@/components/ui/Panel';
import { getRepositories } from '@/persistence/repositories';
import { useAnalysisPosition } from '@/features/analysis/useAnalysisPosition';
import { useChessWorkspace } from '@/features/workspace/ChessWorkspaceContext';
import { useAnalysis } from '@/stores/analysis-store';
import { useUi } from '@/stores/ui-store';
import { cn } from '@/lib/cn';

import {
  formatRoute,
  mergeRoutes,
  ROUTE_SOURCE_LABEL,
  routesFromTree,
  type MergedRoute,
  type TranspositionRouteView,
} from './transpositions';

/** Enough to see the pattern; more is a census, not evidence. */
const INITIAL = 4;

export function TranspositionsPanel() {
  const { node } = useAnalysisPosition();
  const { tree, currentId } = useChessWorkspace();
  const [expanded, setExpanded] = useState(false);
  const key = positionKey(node.fen);

  const routes = useQuery({
    queryKey: ['transpositions', key],
    staleTime: 60_000,
    retry: false,
    queryFn: async (): Promise<readonly TranspositionRouteView[]> => {
      const repositories = await getRepositories();
      const [fromGames, studies] = await Promise.all([
        repositories.games.routesToPosition(key, 8),
        repositories.studies.list(),
      ]);

      const collected: TranspositionRouteView[] = fromGames.map((route) => ({
        moves: route.moves,
        count: route.games,
        source: 'local-games' as const,
      }));

      /*
        Chapters are read study by study rather than through one flat query
        because a chapter's title is only meaningful next to its study's. The
        cost is bounded by how many studies exist, which is a human number.
      */
      for (const study of studies) {
        const loaded = await repositories.studies.get(study.id);
        for (const chapter of loaded?.chapters ?? []) {
          collected.push(
            ...routesFromTree(chapter.tree, key, {
              label: `${study.title} · ${chapter.title}`,
              chapterId: chapter.id,
            }),
          );
        }
      }

      return collected;
    },
  });

  // The order the user is on now, so it is not offered back to them.
  const currentMoves = useMemo(() => {
    void currentId;
    return mainlinePath(tree)
      .slice(1)
      .map((id) => mustGetNode(tree, id).move?.san)
      .filter((san): san is San => san !== undefined);
  }, [tree, currentId]);

  const merged = useMemo(
    () => mergeRoutes(routes.data ?? [], currentMoves),
    [routes.data, currentMoves],
  );

  const shown = expanded ? merged : merged.slice(0, INITIAL);

  return (
    <div className="flex h-full min-h-0 flex-col">
      <PanelHeader>Transpositions</PanelHeader>
      <PanelBody>
        {routes.isPending ? (
          <p className="px-3 py-5 text-2xs text-tertiary">Reading stored move orders…</p>
        ) : routes.isError ? (
          <EmptyState
            title="Move orders could not be read."
            description={
              routes.error instanceof Error ? routes.error.message : 'The lookup failed.'
            }
          />
        ) : merged.length === 0 ? (
          <EmptyState
            title="No other move order reaches this position."
            description="Only orders that appear in your games or your studies are listed. Nothing is generated by searching for legal alternatives."
          />
        ) : (
          <div className="divide-y divide-line-subtle">
            {shown.map((route) => (
              <RouteRow key={route.signature} route={route} />
            ))}
            {merged.length > INITIAL && (
              <button
                type="button"
                onClick={() => setExpanded(!expanded)}
                className="w-full px-3 py-2 text-left text-2xs text-accent hover:bg-surface-2"
              >
                {expanded ? 'Show fewer' : `Show ${merged.length - INITIAL} more`}
              </button>
            )}
          </div>
        )}
      </PanelBody>
    </div>
  );
}

function RouteRow({ route }: { route: MergedRoute }) {
  const setNotice = useUi((state) => state.notify);
  const openDocument = useAnalysis((state) => state.openDocument);

  const open = async () => {
    const target = route.openable;
    if (!target) return;
    try {
      const repositories = await getRepositories();
      const chapter = await repositories.studies.getChapter(target.chapterId);
      if (!chapter) throw new Error('That chapter no longer exists.');
      const study = await repositories.studies.get(chapter.studyId);
      openDocument({
        tree: chapter.tree,
        document: {
          kind: 'study-chapter',
          title: chapter.title,
          studyId: chapter.studyId,
          studyTitle: study?.study.title ?? 'Study',
          chapterId: chapter.id,
          revision: chapter.revision,
        },
        // The node this route arrives at, so the chapter opens on the position
        // the user was looking at rather than at its first move.
        ...(chapter.tree.nodes[target.nodeId] ? { currentId: target.nodeId } : {}),
      });
    } catch (error) {
      setNotice({
        tone: 'error',
        message: 'That chapter could not be opened.',
        detail: error instanceof Error ? error.message : undefined,
      });
    }
  };

  const provenance = route.bySource
    .map((entry) => `${entry.count} in ${ROUTE_SOURCE_LABEL[entry.source]}`)
    .join(' · ');

  const body = (
    <>
      <p className="font-mono text-xs leading-relaxed text-primary">{formatRoute(route.moves)}</p>
      <p className="mt-0.5 text-[10px] text-tertiary">
        {provenance}
        {route.openable ? ` · ${route.openable.label}` : ''}
      </p>
    </>
  );

  if (!route.openable) return <div className="px-3 py-2">{body}</div>;

  return (
    <button
      type="button"
      onClick={() => void open()}
      className={cn(
        'block w-full px-3 py-2 text-left transition-colors hover:bg-surface-2',
        'focus-visible:outline focus-visible:outline-1 focus-visible:outline-accent',
      )}
      title="Open the chapter this move order comes from"
    >
      {body}
    </button>
  );
}
